#!/bin/bash
set -e

dateString=$(date '+%Y%m%d')

# Run from the directory containing this script, regardless of where it's
# invoked or which machine/username it lives on.
cd "$(dirname "$0")"

name=$1

# Lectures live in slides/150/; standalone talks live flat in slides/.
# Prefer the 150 subdir, fall back to the flat layout.
if test -f "slides/150/$name.tex"; then
  slidedir="slides/150"
else
  slidedir="slides"
fi

# Title image is optional; only stage it if one exists for this slide deck.
if test -f "img/$name.png"; then
  cp "img/$name.png" img/title.png
fi

# Code fragments are only sliced when a code/ tree exists for this deck.
if test -d "code/$name"; then
  ./slice "$name"
fi

if test -f "$slidedir/$name.m4"; then
  echo "has an m4 file"
  m4 "$slidedir/$name.m4" "$slidedir/$name.tex" > "$slidedir/$name-intermediate.tex"
  make pdf "SRC=$slidedir/$name-intermediate.tex" "PREFIX=$name" "NUM=$name"
  rm "$slidedir/$name-intermediate.tex"
else
  make pdf "SRC=$slidedir/$name.tex" "PREFIX=$name" "NUM=$name"
fi

rm -f img/title.png
